import json

# Load the notebook
with open('notebooks/training.ipynb', 'r', encoding='utf-8') as f:
    nb = json.load(f)

# Cell 4: Features and Dataset generation
cell_4_source = [
    "def compute_engineered_features(X_base: np.ndarray) -> np.ndarray:\n",
    "    \"\"\"\n",
    "    Tambahkan 5 fitur turunan dari 8 fitur dasar.\n",
    "    \n",
    "    Input X_base kolom (index):\n",
    "        0: kondisi_rumah (1-5)\n",
    "        1: sumber_listrik (1-4)\n",
    "        2: kepemilikan_aset (1-4)\n",
    "        3: pendidikan_kk (1-6)\n",
    "        4: jml_tanggungan (0-12)\n",
    "        5: jenis_pekerjaan (1-6)\n",
    "        6: akses_air (1-4)\n",
    "        7: kepemilikan_lahan (1-3)\n",
    "    \n",
    "    Output: X_base + 5 kolom baru (total 13 kolom)\n",
    "    \"\"\"\n",
    "    kondisi_rumah     = X_base[:, 0]\n",
    "    sumber_listrik    = X_base[:, 1]\n",
    "    kepemilikan_aset  = X_base[:, 2]\n",
    "    pendidikan_kk     = X_base[:, 3]\n",
    "    jml_tanggungan    = X_base[:, 4]\n",
    "    jenis_pekerjaan   = X_base[:, 5]\n",
    "    akses_air         = X_base[:, 6]\n",
    "    kepemilikan_lahan = X_base[:, 7]\n",
    "\n",
    "    # 1. Skor kerentanan (weighted sum \u2014 semakin tinggi = semakin baik)\n",
    "    skor_kerentanan = (\n",
    "        kondisi_rumah * 2.0 +\n",
    "        sumber_listrik * 1.5 +\n",
    "        kepemilikan_aset * 2.5 +\n",
    "        pendidikan_kk * 1.0 +\n",
    "        jenis_pekerjaan * 2.0 +\n",
    "        akses_air * 1.5 +\n",
    "        kepemilikan_lahan * 2.0 -\n",
    "        jml_tanggungan * 1.5\n",
    "    )\n",
    "\n",
    "    # 2. Rasio tanggungan terhadap aset\n",
    "    rasio_tanggungan_aset = jml_tanggungan / (kepemilikan_aset + kepemilikan_lahan + 0.5)\n",
    "\n",
    "    # 3. Skor infrastruktur\n",
    "    skor_infrastruktur = sumber_listrik + akses_air\n",
    "\n",
    "    # 4. Skor ekonomi\n",
    "    skor_ekonomi = jenis_pekerjaan + kepemilikan_aset + kepemilikan_lahan\n",
    "\n",
    "    # 5. Interaksi pendidikan \u00d7 pekerjaan\n",
    "    interaksi_pend_kerja = pendidikan_kk * jenis_pekerjaan\n",
    "\n",
    "    # Stack semua fitur\n",
    "    engineered = np.column_stack([\n",
    "        skor_kerentanan,\n",
    "        rasio_tanggungan_aset,\n",
    "        skor_infrastruktur,\n",
    "        skor_ekonomi,\n",
    "        interaksi_pend_kerja,\n",
    "    ])\n",
    "\n",
    "    return np.hstack([X_base, engineered])\n",
    "\n",
    "\n",
    "def generate_synthetic_dataset_v2(n_samples: int = 15000, seed: int = 42) -> pd.DataFrame:\n",
    "    \"\"\"\n",
    "    Generate dataset sintetis berbasis distribusi BPS Aceh v2.\n",
    "    \n",
    "    Perbaikan: distribusi antar kelas dibuat LEBIH TERPISAH agar\n",
    "    setiap level memiliki 'signature' yang lebih jelas.\n",
    "\n",
    "    Label:\n",
    "    - Level 1 (Miskin Ekstrem): profil dominan di nilai RENDAH (buruk)\n",
    "    - Level 2 (Miskin): profil di TENGAH, distribusi lebih focused\n",
    "    - Level 3 (Rentan Miskin): profil dominan di nilai TINGGI (baik)\n",
    "    \"\"\"\n",
    "    rng = np.random.default_rng(seed)\n",
    "\n",
    "    # Proporsi target\n",
    "    proportions = {1: 0.25, 2: 0.45, 3: 0.30}\n",
    "    counts = {k: int(v * n_samples) for k, v in proportions.items()}\n",
    "    counts[2] += n_samples - sum(counts.values())\n",
    "\n",
    "    records = []\n",
    "\n",
    "    for level, n in counts.items():\n",
    "        if level == 1:  # MISKIN EKSTREM \u2014 profil kerentanan TINGGI\n",
    "            data = {\n",
    "                'kondisi_rumah': rng.choice([1, 2, 3], size=n, p=[0.65, 0.30, 0.05]),\n",
    "                'sumber_listrik': rng.choice([1, 2, 3, 4], size=n, p=[0.45, 0.35, 0.15, 0.05]),\n",
    "                'kepemilikan_aset': rng.choice([1, 2, 3, 4], size=n, p=[0.75, 0.20, 0.04, 0.01]),\n",
    "                'pendidikan_kk': rng.choice([1, 2, 3, 4, 5, 6], size=n, p=[0.45, 0.35, 0.13, 0.05, 0.015, 0.005]),\n",
    "                'jml_tanggungan': rng.choice(range(0, 13), size=n,\n",
    "                    p=[0.01, 0.01, 0.02, 0.04, 0.07, 0.12, 0.18, 0.19, 0.15, 0.10, 0.06, 0.03, 0.02]),\n",
    "                'jenis_pekerjaan': rng.choice([1, 2, 3, 4, 5, 6], size=n, p=[0.45, 0.30, 0.15, 0.06, 0.03, 0.01]),\n",
    "                'akses_air': rng.choice([1, 2, 3, 4], size=n, p=[0.45, 0.35, 0.15, 0.05]),\n",
    "                'kepemilikan_lahan': rng.choice([1, 2, 3], size=n, p=[0.70, 0.20, 0.10]),\n",
    "                'level_subsidi': np.full(n, 1),\n",
    "            }\n",
    "\n",
    "        elif level == 2:  # MISKIN \u2014 profil kerentanan SEDANG (focused di tengah)\n",
    "            data = {\n",
    "                'kondisi_rumah': rng.choice([1, 2, 3, 4, 5], size=n, p=[0.08, 0.32, 0.40, 0.15, 0.05]),\n",
    "                'sumber_listrik': rng.choice([1, 2, 3, 4], size=n, p=[0.05, 0.20, 0.55, 0.20]),\n",
    "                'kepemilikan_aset': rng.choice([1, 2, 3, 4], size=n, p=[0.20, 0.50, 0.25, 0.05]),\n",
    "                'pendidikan_kk': rng.choice([1, 2, 3, 4, 5, 6], size=n, p=[0.05, 0.20, 0.40, 0.25, 0.07, 0.03]),\n",
    "                'jml_tanggungan': rng.choice(range(0, 13), size=n,\n",
    "                    p=[0.02, 0.05, 0.10, 0.18, 0.22, 0.18, 0.12, 0.07, 0.03, 0.015, 0.01, 0.003, 0.002]),\n",
    "                'jenis_pekerjaan': rng.choice([1, 2, 3, 4, 5, 6], size=n, p=[0.05, 0.15, 0.35, 0.25, 0.15, 0.05]),\n",
    "                'akses_air': rng.choice([1, 2, 3, 4], size=n, p=[0.05, 0.25, 0.50, 0.20]),\n",
    "                'kepemilikan_lahan': rng.choice([1, 2, 3], size=n, p=[0.25, 0.45, 0.30]),\n",
    "                'level_subsidi': np.full(n, 2),\n",
    "            }\n",
    "\n",
    "        else:  # RENTAN MISKIN \u2014 profil kerentanan RENDAH (fokus di nilai tinggi)\n",
    "            data = {\n",
    "                'kondisi_rumah': rng.choice([1, 2, 3, 4, 5], size=n, p=[0.02, 0.05, 0.18, 0.40, 0.35]),\n",
    "                'sumber_listrik': rng.choice([1, 2, 3, 4], size=n, p=[0.01, 0.04, 0.25, 0.70]),\n",
    "                'kepemilikan_aset': rng.choice([1, 2, 3, 4], size=n, p=[0.05, 0.15, 0.45, 0.35]),\n",
    "                'pendidikan_kk': rng.choice([1, 2, 3, 4, 5, 6], size=n, p=[0.02, 0.08, 0.15, 0.35, 0.25, 0.15]),\n",
    "                'jml_tanggungan': rng.choice(range(0, 13), size=n,\n",
    "                    p=[0.08, 0.15, 0.22, 0.22, 0.15, 0.08, 0.05, 0.03, 0.01, 0.005, 0.003, 0.001, 0.001]),\n",
    "                'jenis_pekerjaan': rng.choice([1, 2, 3, 4, 5, 6], size=n, p=[0.02, 0.05, 0.10, 0.25, 0.30, 0.28]),\n",
    "                'akses_air': rng.choice([1, 2, 3, 4], size=n, p=[0.01, 0.05, 0.30, 0.64]),\n",
    "                'kepemilikan_lahan': rng.choice([1, 2, 3], size=n, p=[0.05, 0.15, 0.80]),\n",
    "                'level_subsidi': np.full(n, 3),\n",
    "            }\n",
    "\n",
    "        records.append(pd.DataFrame(data))\n",
    "\n",
    "    df = pd.concat(records, ignore_index=True)\n",
    "    df = df.sample(frac=1, random_state=seed).reset_index(drop=True)  # Acak urutan\n",
    "    return df\n",
    "\n",
    "\n",
    "df = generate_synthetic_dataset_v2(n_samples=15000)\n",
    "print(f'Dataset berhasil dibuat: {df.shape[0]} baris, {df.shape[1]} kolom')\n",
    "print(f'\\nDistribusi label:')\n",
    "print(df['level_subsidi'].value_counts().sort_index())\n",
    "print(f'\\nSample data:')\n",
    "df.head(10)"
]
nb['cells'][4]['source'] = cell_4_source

# Cell 9: Feature Columns
cell_9_source = [
    "FEATURE_COLS = [\n",
    "    'kondisi_rumah', 'sumber_listrik', 'kepemilikan_aset', 'pendidikan_kk',\n",
    "    'jml_tanggungan', 'jenis_pekerjaan', 'akses_air', 'kepemilikan_lahan'\n",
    "]\n",
    "TARGET_COL = 'level_subsidi'\n",
    "\n",
    "X_base = df[FEATURE_COLS].values\n",
    "y = df[TARGET_COL].values\n",
    "\n",
    "# Feature engineering\n",
    "X = compute_engineered_features(X_base)\n",
    "\n",
    "# Split stratified: 70% train, 15% val, 15% test\n",
    "X_temp, X_test, y_temp, y_test = train_test_split(\n",
    "    X, y, test_size=0.15, random_state=42, stratify=y\n",
    ")\n",
    "X_train, X_val, y_train, y_val = train_test_split(\n",
    "    X_temp, y_temp, test_size=0.176, random_state=42, stratify=y_temp  # 0.176 \u2248 15% dari total\n",
    ")\n",
    "\n",
    "print(f'Train : {X_train.shape[0]} sampel')\n",
    "print(f'Val   : {X_val.shape[0]} sampel')\n",
    "print(f'Test  : {X_test.shape[0]} sampel')\n",
    "print(f'\\nDistribusi kelas train:')\n",
    "unique, counts = np.unique(y_train, return_counts=True)\n",
    "for u, c in zip(unique, counts):\n",
    "    print(f'  Level {u}: {c} ({c/len(y_train)*100:.1f}%)')"
]
nb['cells'][9]['source'] = cell_9_source

# Cell 12: Models hyperparameters and evaluation
cell_12_source = [
    "# XGBoost perlu label dimulai dari 0\n",
    "y_train_xgb = y_train_res - 1\n",
    "y_val_xgb = y_val - 1\n",
    "y_test_xgb = y_test - 1\n",
    "\n",
    "models = {\n",
    "    'XGBoost': XGBClassifier(\n",
    "        n_estimators=500,\n",
    "        max_depth=8,\n",
    "        learning_rate=0.03,\n",
    "        subsample=0.8,\n",
    "        colsample_bytree=0.8,\n",
    "        min_child_weight=3,\n",
    "        gamma=0.1,\n",
    "        reg_alpha=0.1,\n",
    "        reg_lambda=1.0,\n",
    "        use_label_encoder=False,\n",
    "        eval_metric='mlogloss',\n",
    "        random_state=42,\n",
    "        n_jobs=-1,\n",
    "    ),\n",
    "    'LightGBM': LGBMClassifier(\n",
    "        n_estimators=500,\n",
    "        max_depth=8,\n",
    "        learning_rate=0.03,\n",
    "        subsample=0.8,\n",
    "        colsample_bytree=0.8,\n",
    "        min_child_samples=10,\n",
    "        reg_alpha=0.1,\n",
    "        reg_lambda=1.0,\n",
    "        random_state=42,\n",
    "        n_jobs=-1,\n",
    "        verbose=-1,\n",
    "    ),\n",
    "    'Random Forest': RandomForestClassifier(\n",
    "        n_estimators=500,\n",
    "        max_depth=15,\n",
    "        min_samples_split=5,\n",
    "        min_samples_leaf=2,\n",
    "        random_state=42,\n",
    "        n_jobs=-1,\n",
    "    ),\n",
    "    'Logistic Regression': LogisticRegression(\n",
    "        max_iter=2000,\n",
    "        random_state=42,\n",
    "        n_jobs=-1,\n",
    "        multi_class='ovr',\n",
    "        C=0.5,\n",
    "    ),\n",
    "}\n",
    "\n",
    "results = {}\n",
    "\n",
    "for name, model in models.items():\n",
    "    print(f'\\n[OK] Training {name}...')\n",
    "\n",
    "    # XGBoost pakai label 0-2, sisanya 1-3\n",
    "    is_xgb = isinstance(model, XGBClassifier)\n",
    "    _y_train = y_train_xgb if is_xgb else y_train_res\n",
    "    _y_val   = y_val_xgb   if is_xgb else y_val\n",
    "    _y_test  = y_test_xgb  if is_xgb else y_test\n",
    "\n",
    "    model.fit(X_train_res, _y_train)\n",
    "\n",
    "    # Prediksi\n",
    "    y_pred = model.predict(X_test)\n",
    "\n",
    "    # Koreksi label XGBoost kembali ke 1-3\n",
    "    if is_xgb:\n",
    "        y_pred = y_pred + 1\n",
    "        _y_test_eval = y_test  # Gunakan label asli 1-3 untuk evaluasi\n",
    "    else:\n",
    "        _y_test_eval = y_test\n",
    "\n",
    "    acc = accuracy_score(_y_test_eval, y_pred)\n",
    "    f1  = f1_score(_y_test_eval, y_pred, average='weighted')\n",
    "    f1_macro = f1_score(_y_test_eval, y_pred, average='macro')\n",
    "\n",
    "    results[name] = {\n",
    "        'model'    : model,\n",
    "        'accuracy' : acc,\n",
    "        'f1_weighted': f1,\n",
    "        'f1_macro' : f1_macro,\n",
    "        'y_pred'   : y_pred,\n",
    "        'is_xgb'   : is_xgb,\n",
    "    }\n",
    "\n",
    "    print(f'  [OK] Accuracy : {acc:.4f}')\n",
    "    print(f'     F1 (weighted): {f1:.4f}')\n",
    "    print(f'     F1 (macro)  : {f1_macro:.4f}')"
]
nb['cells'][12]['source'] = cell_12_source

with open('notebooks/training.ipynb', 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1)
